columnlines<-c("black","red","blue")
caption<-c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
plot(powerdata$datetime,powerdata$Sub_metering_1,type="lines",col=columnlines[1],xlab = "",ylab = "Energy sub metering")
lines(powerdata$datetime,powerdata$Sub_metering_2,col=columnlines[2])
lines(powerdata$datetime,powerdata$Sub_metering_3,col=columnlines[3])
legend("topright",col = columnlines,legend = caption,lty = "solid")